# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.manager:
    build:
      context: wazuh-manager/
      args:
        WAZUH_VERSION: ${WAZUH_VERSION}
        WAZUH_TAG_REVISION: ${WAZUH_TAG_REVISION}
        FILEBEAT_TEMPLATE_BRANCH: ${FILEBEAT_TEMPLATE_BRANCH}
        WAZUH_FILEBEAT_MODULE: ${WAZUH_FILEBEAT_MODULE}
    image: wazuh/wazuh-manager:${WAZUH_IMAGE_VERSION}
    hostname: wazuh.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=none
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat

  wazuh.indexer:
    build:
      context: wazuh-indexer/
      args:
        WAZUH_VERSION: ${WAZUH_VERSION}
        WAZUH_TAG_REVISION: ${WAZUH_TAG_REVISION}
    image: wazuh/wazuh-indexer:${WAZUH_IMAGE_VERSION}
    hostname: wazuh.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  wazuh.dashboard:
    build:
      context: wazuh-dashboard/
      args:
        WAZUH_VERSION: ${WAZUH_VERSION}
        WAZUH_TAG_REVISION: ${WAZUH_TAG_REVISION}
        WAZUH_UI_REVISION: ${WAZUH_UI_REVISION}
    image: wazuh/wazuh-dashboard:${WAZUH_IMAGE_VERSION}
    hostname: wazuh.dashboard
    restart: always
    ports:
      - 443:443
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - SERVER_SSL_ENABLED=false
      - WAZUH_API_URL=https://wazuh.manager
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager

  wazuh.fluentd:
    build:
      context: wazuh-fluentd/
    image: wazuh/wazuh-fluentd:${WAZUH_IMAGE_VERSION}
    hostname: wazuh.fluentd
    restart: always
    ports:
      - "2055:2055/udp"    # NetFlow/IPFIX
      - "6343:6343/udp"    # sFlow
      - "40514:40514/udp"  # MikroTik
      - "40515:40515/tcp"  # Fortigate CEF
      - "40516:40516/udp"  # Fortigate Syslog
      - "40517:40517/udp"  # Cisco ASA
      - "40518:40518/tcp"  # Palo Alto
      - "40519:40519/udp"  # Generic Syslog UDP
      - "40520:40520/tcp"  # Generic Syslog TCP
      - "40521:40521/tcp"  # Generic CEF TCP
      - "40522:40522/udp"  # Generic CEF UDP
      - "40523:40523/udp"  # Ruckus UDP
      - "40524:40524/tcp"  # Ruckus TCP
      - "40525:40525/tcp"  # Checkpoint CEF
      - "40526:40526/udp"  # Checkpoint Syslog
    environment:
      - INDEXER_HOST=wazuh.indexer
      - INDEXER_PORT=9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - SETUP_PIPELINES=true
      - FLUENTD_LOG_LEVEL=info
    volumes:
      - fluentd_buffer:/fluentd/buffer
      - fluentd_logs:/fluentd/log
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_active_response:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  fluentd_buffer:
  fluentd_logs:
