version: "3.8"

# Example Docker Compose configuration for Wazuh Fluentd
# This can be used standalone or integrated with your Wazuh stack

services:
  wazuh-fluentd:
    image: wazuh/wazuh-fluentd:4.13.1
    container_name: wazuh-fluentd
    hostname: wazuh-fluentd
    restart: unless-stopped

    # Expose syslog ports
    ports:
      # Syslog receivers
      - "514:514/udp"        # Generic syslog
      - "30514:30514/udp"    # MikroTik
      - "30527:30527/udp"    # VMware ESXi
      # NetFlow receiver
      - "2055:2055/udp"      # NetFlow v5/v9/v10 (IPFIX)

    environment:
      # Required: Wazuh Indexer connection
      - INDEXER_HOST=wazuh-indexer
      - INDEXER_PORT=9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword # Change this!

      # Required: Wazuh Manager connection (for security rules)
      - WAZUH_MANAGER_HOST=wazuh-manager
      - WAZUH_MANAGER_PORT=1514

      # Optional: Pipeline setup
      - SETUP_PIPELINES=true # Auto-create pipelines on startup

      # Optional: Fluentd configuration
      - FLUENTD_LOG_LEVEL=info # debug, info, warn, error
      - FLUENTD_WORKERS=1 # Increase for high-volume

    volumes:
      # Persistent buffer storage (recommended)
      - fluentd-buffer:/fluentd/buffer
      - fluentd-logs:/fluentd/log

      # Optional: Custom configurations
      # - ./custom-conf.d:/fluentd/etc/conf.d:ro
      # - ./custom-pipelines:/fluentd/pipelines:ro

    networks:
      - wazuh

    # Optional: Resource limits
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

volumes:
  fluentd-buffer:
    driver: local
  fluentd-logs:
    driver: local

networks:
  wazuh:
    # If using with existing Wazuh stack, use:
    # external: true
    driver: bridge
