---
# Fluentd Custom Image Deployment
# Deploys custom ghcr.io/anki-security/wazuh-fluentd image with built-in configs
#
# Configuration variables: fluentd_storage_size, fluentd_cpu_request, etc.
# Deployment condition: fluentd_storage_size must be defined in group_vars

- name: "Display {{ ansible_k8s_namespace }} Fluentd deployment info"
  debug:
    msg: |
      🚀 Deploying Custom Fluentd for {{ ansible_k8s_namespace }}
      
      📊 Configuration:
      - Image: ghcr.io/anki-security/wazuh-fluentd:latest
      - Storage: {{ fluentd_storage_size | default('2Gi') }}
      - CPU Request: {{ fluentd_cpu_request | default('100m') }}
      - Memory Request: {{ fluentd_memory_request | default('256Mi') }}
      - Log Level: {{ fluentd_log_level | default('info') }}
      
      🔌 Supported Protocols (all built-in):
      - NetFlow/IPFIX (2055/UDP)
      - sFlow (6343/UDP)
      - MikroTik (30514/UDP)
      - Fortigate CEF (30515/TCP) & Syslog (30516/UDP)
      - Cisco ASA (30517/UDP)
      - Palo Alto (30518/TCP)
      - Generic Syslog (30519/UDP, 30520/TCP)
      - Generic CEF (30521/TCP, 30522/UDP)
      - Ruckus (30523/UDP, 30524/TCP)
      - Check Point CEF (30525/TCP) & Syslog (30526/UDP)
      
      ✨ Features:
      - Built-in configurations and parsers
      - Automatic pipeline setup (SETUP_PIPELINES=true)
      - All vendor formats supported out-of-the-box

- name: "Deploy {{ ansible_k8s_namespace }} Fluentd StatefulSet"
  include_tasks: fluentd-statefulset.yml
