name: Build and Push Wazuh Docker Images

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Version bump type (or 'none' to use current)"
        required: true
        default: "none"
        type: choice
        options:
          - none
          - patch
          - minor
          - major
      push_images:
        description: 'Push images to registry'
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/anki-security

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read current version
        id: current_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' VERSION.json)
          WAZUH_VERSION=$(jq -r '.wazuh_version' VERSION.json)
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "wazuh_version=$WAZUH_VERSION" >> $GITHUB_OUTPUT
          echo "Current custom version: $CURRENT_VERSION"
          echo "Wazuh upstream version: $WAZUH_VERSION"
          
      - name: Bump version
        id: bump_version
        run: |
          CURRENT_VERSION="${{ steps.current_version.outputs.version }}"
          
          if [ "${{ github.event.inputs.bump_type }}" == "none" ]; then
            NEW_VERSION="$CURRENT_VERSION"
            echo "Using current version: $NEW_VERSION"
          else
            IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
            
            case "${{ github.event.inputs.bump_type }}" in
              major)
                major=$((major + 1))
                minor=0
                patch=0
                ;;
              minor)
                minor=$((minor + 1))
                patch=0
                ;;
              patch)
                patch=$((patch + 1))
                ;;
            esac
            
            NEW_VERSION="${major}.${minor}.${patch}"
            echo "Bumped version: $CURRENT_VERSION -> $NEW_VERSION"
            
            # Update VERSION.json
            jq --arg version "$NEW_VERSION" '.version = $version' VERSION.json > VERSION.json.tmp
            mv VERSION.json.tmp VERSION.json
          fi
          
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Wazuh images
        run: |
          WAZUH_VERSION="${{ steps.current_version.outputs.wazuh_version }}"
          echo "Building with Wazuh version: $WAZUH_VERSION"
          ./build-images.sh -v $WAZUH_VERSION

      - name: Tag images for GHCR
        run: |
          WAZUH_VERSION="${{ steps.current_version.outputs.wazuh_version }}"
          CUSTOM_VERSION="${{ steps.bump_version.outputs.version }}"
          
          echo "Tagging images: Wazuh $WAZUH_VERSION as custom version $CUSTOM_VERSION"
          
          # Tag wazuh-manager
          docker tag wazuh/wazuh-manager:$WAZUH_VERSION ${{ env.IMAGE_PREFIX }}/wazuh-manager:$CUSTOM_VERSION
          docker tag wazuh/wazuh-manager:$WAZUH_VERSION ${{ env.IMAGE_PREFIX }}/wazuh-manager:latest
          
          # Tag wazuh-indexer
          docker tag wazuh/wazuh-indexer:$WAZUH_VERSION ${{ env.IMAGE_PREFIX }}/wazuh-indexer:$CUSTOM_VERSION
          docker tag wazuh/wazuh-indexer:$WAZUH_VERSION ${{ env.IMAGE_PREFIX }}/wazuh-indexer:latest
          
          # Tag wazuh-dashboard
          docker tag wazuh/wazuh-dashboard:$WAZUH_VERSION ${{ env.IMAGE_PREFIX }}/wazuh-dashboard:$CUSTOM_VERSION
          docker tag wazuh/wazuh-dashboard:$WAZUH_VERSION ${{ env.IMAGE_PREFIX }}/wazuh-dashboard:latest

      - name: Push images to GHCR
        if: github.event_name != 'pull_request' && (github.event_name != 'workflow_dispatch' || inputs.push_images)
        run: |
          CUSTOM_VERSION="${{ steps.bump_version.outputs.version }}"
          
          echo "Pushing wazuh-manager..."
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-manager:$CUSTOM_VERSION
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-manager:latest
          
          echo "Pushing wazuh-indexer..."
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-indexer:$CUSTOM_VERSION
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-indexer:latest
          
          echo "Pushing wazuh-dashboard..."
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-dashboard:$CUSTOM_VERSION
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-dashboard:latest

      - name: Commit version bump
        if: github.event.inputs.bump_type != 'none'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add VERSION.json
          git commit -m "chore: bump Wazuh version to ${{ steps.bump_version.outputs.version }}"
          git tag -a "v${{ steps.bump_version.outputs.version }}" -m "Release v${{ steps.bump_version.outputs.version }}"

      - name: Push changes
        if: github.event.inputs.bump_type != 'none'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Image summary
        run: |
          WAZUH_VERSION="${{ steps.current_version.outputs.wazuh_version }}"
          CUSTOM_VERSION="${{ steps.bump_version.outputs.version }}"
          echo "## Built Images" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Wazuh Version:** $WAZUH_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "**Custom Version:** $CUSTOM_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.IMAGE_PREFIX }}/wazuh-manager:$CUSTOM_VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.IMAGE_PREFIX }}/wazuh-indexer:$CUSTOM_VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.IMAGE_PREFIX }}/wazuh-dashboard:$CUSTOM_VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All images are also tagged as \`:latest\`" >> $GITHUB_STEP_SUMMARY
