name: Build and Push Wazuh Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Wazuh version to build'
        required: false
        default: '4.13.1'
      push_images:
        description: 'Push images to registry'
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/anki-security

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION=$(jq -r '.version' VERSION.json)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Build Wazuh images
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          ./build-images.sh -v $VERSION

      - name: Tag images for GHCR
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          
          # Tag wazuh-manager
          docker tag wazuh/wazuh-manager:$VERSION ${{ env.IMAGE_PREFIX }}/wazuh-manager:$VERSION
          docker tag wazuh/wazuh-manager:$VERSION ${{ env.IMAGE_PREFIX }}/wazuh-manager:latest
          
          # Tag wazuh-indexer
          docker tag wazuh/wazuh-indexer:$VERSION ${{ env.IMAGE_PREFIX }}/wazuh-indexer:$VERSION
          docker tag wazuh/wazuh-indexer:$VERSION ${{ env.IMAGE_PREFIX }}/wazuh-indexer:latest
          
          # Tag wazuh-dashboard
          docker tag wazuh/wazuh-dashboard:$VERSION ${{ env.IMAGE_PREFIX }}/wazuh-dashboard:$VERSION
          docker tag wazuh/wazuh-dashboard:$VERSION ${{ env.IMAGE_PREFIX }}/wazuh-dashboard:latest

      - name: Push images to GHCR
        if: github.event_name != 'pull_request' && (github.event_name != 'workflow_dispatch' || inputs.push_images)
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          
          echo "Pushing wazuh-manager..."
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-manager:$VERSION
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-manager:latest
          
          echo "Pushing wazuh-indexer..."
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-indexer:$VERSION
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-indexer:latest
          
          echo "Pushing wazuh-dashboard..."
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-dashboard:$VERSION
          docker push ${{ env.IMAGE_PREFIX }}/wazuh-dashboard:latest

      - name: Image summary
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "## Built Images" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.IMAGE_PREFIX }}/wazuh-manager:$VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.IMAGE_PREFIX }}/wazuh-indexer:$VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.IMAGE_PREFIX }}/wazuh-dashboard:$VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All images are also tagged as \`:latest\`" >> $GITHUB_STEP_SUMMARY
